echo '<?xml version="1.0" encoding="UTF-8"?>'
echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
echo '<plist version="1.0">'
echo '     <dict>'
echo '             <key>SeedProgram</key>'
echo '             <string>DeveloperSeed</string>'
echo '     </dict>'
echo '</plist>'
